export const CHANGE_STADIUM = "CHANGE_STADIUM";

export const REQUEST_DATA_PENDING = "REQUEST_DATA_PENDING";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";
